// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEgsdv0s6JiuqPd1HS9MbdUaGyiP6Trs',
    appId: '1:363034307864:web:1e1a37c93db15492c4026d',
    messagingSenderId: '363034307864',
    projectId: 'projet-pfe-3850d',
    authDomain: 'projet-pfe-3850d.firebaseapp.com',
    storageBucket: 'projet-pfe-3850d.appspot.com',
    measurementId: 'G-940MHKZ5G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2nPjtjmecIaUmEJxf-nqugonRQrfiIo',
    appId: '1:363034307864:android:1814de17ca18e298c4026d',
    messagingSenderId: '363034307864',
    projectId: 'projet-pfe-3850d',
    storageBucket: 'projet-pfe-3850d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEQ3ouUM8u8u3ctzOVJHl-oALTWK05WQ',
    appId: '1:363034307864:ios:a257edeacc52f588c4026d',
    messagingSenderId: '363034307864',
    projectId: 'projet-pfe-3850d',
    storageBucket: 'projet-pfe-3850d.appspot.com',
    iosClientId: '363034307864-crb8ppvcht9iofuts0aksqru2hpf5032.apps.googleusercontent.com',
    iosBundleId: 'com.example.deviceToken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEQ3ouUM8u8u3ctzOVJHl-oALTWK05WQ',
    appId: '1:363034307864:ios:a257edeacc52f588c4026d',
    messagingSenderId: '363034307864',
    projectId: 'projet-pfe-3850d',
    storageBucket: 'projet-pfe-3850d.appspot.com',
    iosClientId: '363034307864-crb8ppvcht9iofuts0aksqru2hpf5032.apps.googleusercontent.com',
    iosBundleId: 'com.example.deviceToken',
  );
}
